[package]
name = "tiltify-donation-tailer"
version = "0.1.0"
authors = ["Gary M. Josack <gary@byoteki.com>"]
edition = "2018"

[dependencies]
tiltify = "0.1"
anyhow = "1"
clap = "2"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }